### ISSUE TITLE
Toggling hide/show core members breaks the correct order of the members

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/leaderboard#78] opened 2022-08-31 14:57 UTC
Before Show core members
![image](https://user-images.githubusercontent.com/25143503/187710498-39b26282-8892-476b-9dbc-4b68fc1aff0a.png)

After show core members:

![image](https://user-images.githubusercontent.com/25143503/187710543-9301349c-1346-4b83-844e-200aa28eb6d4.png)

After hide core members:
![image](https://user-images.githubusercontent.com/25143503/187710704-b1b1933c-225c-406f-98be-2a786bc8688f.png)

**Comment by Ritesh-Aggarwal** [comment] 2022-09-01 06:59
@rithviknishad could you please try to reproduce this issue on this [deployment](https://leaderboard-geg66y85l-coronasafe.vercel.app/leaderboard ) , I think this issue has been fixed by #77 as I couldn't reproduce it.

**Comment by rithviknishad** [comment] 2022-09-01 13:02
Yes, it seems to be fixed in that PR.

**Closed** 2022-09-02 15:20 UTC
