### ISSUE TITLE
Typo correction for contributions graph

### ISSUE THREAD

**Issue by anuran-roy** [coronasafe/leaderboard#70] opened 2022-07-05 16:25 UTC
![image](https://user-images.githubusercontent.com/76481787/177373445-01433704-4140-4b92-8ba4-997414341178.png)

There is a small typo in the contributions graph... The year should be 2022, (or rather, the current year)

**Comment by GokulramGHV** [comment] 2022-07-06 09:04
@anuran-roy This issue is a duplicate of #50

**Closed** 2022-09-03 08:37 UTC
Labels: duplicate
