### ISSUE TITLE
Add Hover Effect to GitHub Logo Button in Navbar

### ISSUE THREAD

**Issue by abhinav26966** [coronasafe/leaderboard#497] opened 2024-08-15 13:50 UTC
### Enter your suggestions in details:

Currently, the GitHub logo button in the navbar does not have a hover effect, making it less apparent that it is a clickable element. 
To improve the user experience and visual clarity, we need to add a hover effect to the GitHub logo button. This effect should make the button more recognisable as interactive, aligning it visually with other buttons on the site. 

<img width="1404" alt="Screenshot 2024-08-15 at 7 16 06 PM" src="https://github.com/user-attachments/assets/9977e329-983a-401e-ac1a-b6d96588422e">

Suggestions for the hover effect could include changing the background colour, scaling the logo itself, or any other visual cue that enhances its appearance as a button.

**Comment by abhinav26966** [comment] 2024-08-15 13:51
Hey @rithviknishad, 
I want to work on this issue, can you please assign this issue to me.
It would be a great feature for the website.

**Comment by abhinav26966** [comment] 2024-08-15 14:15
Hey @rithviknishad, 
Can you please check the PR for the issue as it says about the Authorization failed and please help me with the solution for the same.
It would be really helpful for me.

**Comment by abhinav26966** [comment] 2024-08-15 15:49
Hey @rithviknishad, 
Can you please check the PR #500 for the issue as it says about the Authorization failed and please help me with the solution for the same.
It would be really helpful for me.

**Comment by sankshaypusa** [comment] 2024-08-17 02:51
Hi i have added hover effect and raised a PR [PR_RAISED](https://github.com/coronasafe/leaderboard/pull/502) Could you check on it

**Comment by abhinav26966** [comment] 2024-08-18 09:10
Hey @rithviknishad , 
Can you please check the PR #500 and tell if any changes are needed.

**Comment by rithviknishad** [comment] 2024-08-19 11:08
Closing as duplicate of #500

**Closed by rithviknishad** 2024-08-19 11:08 UTC
Labels: feature request
